# Generated by Django 5.2.7 on 2025-11-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create_book', 'Can create book'), ('can_view_book', 'Can view book'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book')]},
        ),
    ]
